// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "fashion",
    platforms: [
        .macOS(.v13),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.5.0"),
    ],
    targets: [
        .target(
            name: "CSSDeep",
            path: "submodules/ssdeep",
            exclude: [
                "AUTHORS",
                "COPYING",
                "ChangeLog",
                "FILEFORMAT",
                "Makefile.am",
                "NEWS",
                "README",
                "TODO",
                "configure.ac",
                "m4",
                "sample.c",
                "ssdeep.1",
                "Doxyfile",
                "INSTALL",
                "bootstrap",
                "normal.sh",
                "test-against-old.sh",
                "win.sh",
                "world.sh",
                "cycles.cpp",
                "dig.cpp",
                "engine.cpp",
                "filedata.cpp",
                "find-file-size.c",
                "helpers.cpp",
                "main.cpp",
                "match.cpp",
                "ui.cpp",
            ],
            sources: [
                "fuzzy.c",
                "edit_dist.c",
            ],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("."),
            ],
        ),
        .target(
            name: "CTLSH",
            path: "submodules/tlsh",
            exclude: [
                "CMakeLists.txt",
                "LICENSE",
                "README.md",
                "README.mingw",
                "README.python",
                "README.windows",
                "NOTICE.txt",
                "PUBLIC.txt",
                "Change_History.md",
                "Testing",
                "test",
                "js_ext",
                "py_ext",
                "java",
                "Windows",
                "mingw",
                "docs",
                "register",
                "tlshCluster",
                "tlsh_bh_tool",
                "utils",
                "clean.sh",
                "clean_mingw.bat",
                "make.sh",
                "make_mingw.bat",
                "2015_Euro_DFRWS_Criteria_Sim_Digests.pdf",
                "Attacking_LSH_and_Sim_Dig.pdf",
                "DFRWS_Similarity_Digests.pdf",
                "TLSH_CTC_final.pdf",
                "TLSH_Introduction.pdf",
                "src/CMakeLists.txt",
                "src/gen_arr2.cpp",
                "src/input_desc.cpp",
                "src/shared_file_functions.cpp",
                "public",
            ],
            sources: [
                "src/tlsh.cpp",
                "src/tlsh_impl.cpp",
                "src/tlsh_util.cpp",
            ],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .define("BUCKETS_128"),
                .define("CHECKSUM_1B"),
            ],
        ),
        .target(
            name: "CTLSHWrapper",
            dependencies: ["CTLSH"],
            path: "Sources/CTLSHWrapper",
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("../../submodules/tlsh/include"),
                .define("BUCKETS_128"),
                .define("CHECKSUM_1B"),
            ],
        ),
        .target(
            name: "CMD5Wrapper",
            path: "Sources/CMD5Wrapper",
            publicHeadersPath: "include",
        ),
        .executableTarget(
            name: "fashion",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                "CSSDeep",
                "CMD5Wrapper",
                "CTLSHWrapper",
            ],
            path: "Sources/fashion",
        ),
        .testTarget(
            name: "fashionTests",
            dependencies: ["fashion"],
            path: "Tests/fashionTests",
        ),
    ],
)
